
name = "DashAutocomplete"
uuid = "1b08a953-4be3-4667-9a23-17f7d8d11c20"
authors = ["Garrett Weaver <gmweaver.usc@gmail.com>"]
version = "0.1.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
